version: '3'
services:

  dremio:
    image: dremio/dremio-oss:$DREMIO_IMAGE_VERSION
    container_name: dremio
    ports:  
      - 9047:9047 
      - 31010:31010 
      - 45678:45678
    volumes:
      - dremio:/opt/dremio/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks: 
  default: 
    external: 
      name: datafuel-local-network

volumes: 
  dremio: